In [2]:
import pandas as pd
import pickle
from math import log
import json
import numpy as np

In [3]:
import sys
sys.path

['/tmp2/wtchiang/CPR_paper/baseline_models/DDTCDR',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/home/wtchiang/.local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.8/dist-packages/IPython/extensions',
 '/home/wtchiang/.ipython']

In [4]:
# tv

In [5]:
tv_interaction_log = pd.read_csv('../../CPR/input/all_tv_train_input.txt', header=None, sep='\t')

In [6]:
tv_interaction_log['user_embedding'] = 0
tv_interaction_log['item_embedding'] = 0
tv_interaction_log.columns=['userID', 'itemID', 'rating', 'user_embedding', 'item_embedding']
tv_interaction_log.head()

,userID,itemID,rating,user_embedding,item_embedding
0,user_00001,tv_1TwM9icNghOGWomKK9hKsijSxWr,0.693147,0,0
1,user_00001,tv_1Tz4SjCxC6dkxjn1dOmcvwmCROt,0.693147,0,0
2,user_00001,tv_1XCSJjYGN7GvZwV2pTuL9QIIHzz,0.693147,0,0
3,user_00001,tv_1XZ2Q4xRZ2S7ye8x5OkQfEWi6cK,1.098612,0,0
4,user_00001,tv_1XZ2QYkNDF5Jm5Yk59lTbVQVH7c,0.693147,0,0

In [7]:
tv_emb = pd.read_csv('../BPR/graph/tv_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
tv_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_00001,-0.106466,1.0,0.025234,0.013047,-0.020633,0.055445,0.026493,-0.022663,-0.025656,...,-0.027203,-0.027456,0.014581,0.018734,-0.004908,0.038573,-0.053696,0.038559,0.053812,-0.036465
1,user_00002,-0.059618,1.0,-0.036562,-0.032341,0.032630,-0.005727,-0.035796,0.030193,0.036509,...,0.033343,0.037538,-0.042023,0.018579,0.031996,-0.019115,0.002681,-0.036669,-0.004699,0.036583
2,user_00003,-0.057363,1.0,-0.038754,-0.032596,0.034908,-0.009571,-0.037896,0.032217,0.038620,...,0.035530,0.039417,-0.042249,0.020028,0.033048,-0.023119,0.004966,-0.039802,-0.008048,0.039302
3,user_00004,-0.126416,1.0,0.011867,-0.001568,-0.009230,0.049424,0.014397,-0.011127,-0.010715,...,-0.015049,-0.013312,-0.006772,0.038560,0.004296,0.031297,-0.050857,0.022875,0.048037,-0.021131
4,user_00005,-0.146779,1.0,0.024827,0.007002,-0.020188,0.060093,0.027436,-0.022488,-0.024271,...,-0.027437,-0.027192,0.003654,0.035976,-0.002029,0.042223,-0.059444,0.038676,0.059182,-0.036791

In [8]:
tv_emb_dict = {}
for i in range(len(tv_emb)):
    k = tv_emb.iloc[i, 0]
    v = list(tv_emb.iloc[i, 3:].values)
    tv_emb_dict[k] = v

In [9]:
tv_interaction_log['user_embedding'] = tv_interaction_log['userID'].map(tv_emb_dict)
tv_interaction_log['item_embedding'] = tv_interaction_log['itemID'].map(tv_emb_dict)

In [10]:
tv_interaction_log.head()

,userID,itemID,rating,user_embedding,item_embedding
0,user_00001,tv_1TwM9icNghOGWomKK9hKsijSxWr,0.693147,"[0.025234083, 0.013047201, -0.020633118, 0.055...","[-0.034191947, -0.025614448, 0.031226488, -0.0..."
1,user_00001,tv_1Tz4SjCxC6dkxjn1dOmcvwmCROt,0.693147,"[0.025234083, 0.013047201, -0.020633118, 0.055...","[-0.0490946, -0.033239603, 0.04459413, -0.0346..."
2,user_00001,tv_1XCSJjYGN7GvZwV2pTuL9QIIHzz,0.693147,"[0.025234083, 0.013047201, -0.020633118, 0.055...","[0.0016112864, 0.00050732424, -0.0015798211, 0..."
3,user_00001,tv_1XZ2Q4xRZ2S7ye8x5OkQfEWi6cK,1.098612,"[0.025234083, 0.013047201, -0.020633118, 0.055...","[0.0044755745, 0.00489287, -0.003918279, 0.003..."
4,user_00001,tv_1XZ2QYkNDF5Jm5Yk59lTbVQVH7c,0.693147,"[0.025234083, 0.013047201, -0.020633118, 0.055...","[0.006086342, 0.0048909215, -0.004988789, 0.00..."

In [ ]:
with open('./input/tv_lightfm.pickle', 'wb') as pf:
    pickle.dump(tv_interaction_log, pf)

In [ ]:
# vod

In [12]:
vod_interaction_log = pd.read_csv('../../CPR/input/vod_train_input.txt', header=None, sep='\t')

In [13]:
vod_interaction_log['user_embedding'] = 0
vod_interaction_log['item_embedding'] = 0
vod_interaction_log.columns=['userID', 'itemID', 'rating', 'user_embedding', 'item_embedding']
vod_interaction_log.head()

,userID,itemID,rating,user_embedding,item_embedding
0,user_00001,vod_1TwKivfISs6XjD3e9hLr0HB1Vu7,1.098612,0,0
1,user_00001,vod_1YQgH9AmANolXlpxhcl0aPdQnZc,1.098612,0,0
2,user_00001,vod_1YQgH9hAyqvY5zYnXCZfU1M9JCk,1.098612,0,0
3,user_00001,vod_1YQgHEZvuEQjk3vKj3FgdCpz2Gq,0.693147,0,0
4,user_00001,vod_1YQgHEa2wy9brUMshRWbpSK00gh,0.693147,0,0

In [14]:
vod_emb = pd.read_csv('../BPR/graph/vod_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
vod_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_00001,-0.334234,1.0,-0.160974,0.194932,0.110631,0.095378,-0.093436,-0.098998,0.240302,...,0.144367,0.080579,0.116898,0.134391,-0.061908,-0.062455,-0.146699,-0.107354,0.149400,-0.021497
1,user_00002,-0.284276,1.0,-0.159439,-0.079047,-0.149365,0.047869,-0.002562,0.011329,-0.115989,...,-0.049689,-0.110606,0.172602,-0.091678,0.044196,-0.005723,0.062953,0.034830,-0.021002,-0.156636
2,user_00003,-0.258264,1.0,-0.032919,-0.141168,0.097090,0.124666,-0.152811,0.084418,0.099458,...,0.042106,-0.128287,-0.011068,-0.058483,0.041869,-0.011182,0.113145,0.100704,-0.139936,-0.086733
3,user_00004,-0.609185,1.0,-0.317403,0.073624,-0.072037,-0.149619,0.112114,-0.072144,0.108132,...,0.015183,0.003843,0.282682,0.025063,-0.001233,-0.028573,0.136231,0.022831,-0.115799,0.044901
4,user_00005,-0.372584,1.0,-0.034461,0.076992,0.198747,-0.013555,-0.152817,-0.049882,0.015519,...,0.001409,-0.057711,-0.170114,0.109487,-0.057509,-0.195496,-0.198649,-0.064582,-0.091343,0.053597

In [ ]:
vod_emb_dict = {}
for i in range(len(vod_emb)):
    k = vod_emb.iloc[i, 0]
    v = list(vod_emb.iloc[i, 3:].values)
    vod_emb_dict[k] = v

In [ ]:
vod_interaction_log['user_embedding'] = vod_interaction_log['userID'].map(vod_emb_dict)
vod_interaction_log['item_embedding'] = vod_interaction_log['itemID'].map(vod_emb_dict)

In [ ]:
vod_interaction_log.head()

In [ ]:
with open('./input/vod_lightfm.pickle', 'wb') as pf:
    pickle.dump(vod_interaction_log, pf)

In [ ]:
total_vod_items = set(vod_interaction_log.itemID)
total_vod_item_emb = {}
for item in total_vod_items:
    total_vod_item_emb[item] = vod_emb_dict[item]

In [ ]:
with open('./input/vod_item_emb_dict.pickle', 'wb') as pf:
    pickle.dump(total_vod_item_emb, pf)

In [ ]:
with open('./input/vod_emb_dict.pickle', 'wb') as pf:
    pickle.dump(vod_emb_dict, pf)

In [ ]:
# csj

In [17]:
csj_interaction_log = pd.read_csv('../../CPR/input/all_csj_train_input.txt', header=None, sep='\t')

In [18]:
csj_interaction_log['user_embedding'] = 0
csj_interaction_log['item_embedding'] = 0
csj_interaction_log.columns=['reviewerID', 'asin', 'rating', 'user_embedding', 'item_embedding']
csj_interaction_log.head()

,reviewerID,asin,rating,user_embedding,item_embedding
0,user_A0003492LQH8LJXPWDMZ,B00I95O5N6,0.693147,0,0
1,user_A0003492LQH8LJXPWDMZ,B00U0I3N4M,0.693147,0,0
2,user_A0003492LQH8LJXPWDMZ,B01FY9XN00,0.693147,0,0
3,user_A0003492LQH8LJXPWDMZ,B01GFN845S,0.693147,0,0
4,user_A001170867ZBE9FORRQL,B001LRNGZC,0.693147,0,0

In [21]:
csj_emb = pd.read_csv('../BPR/graph/csj_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
csj_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_A0003492LQH8LJXPWDMZ,-0.010964,1.0,0.002785,-0.003027,0.002775,-0.002123,-0.004496,-0.004411,0.003989,...,-0.004022,0.001500,-0.002176,-0.004221,0.003019,-0.003463,0.003413,-0.004786,-0.002928,-0.004199
1,user_A001170867ZBE9FORRQL,-0.015678,1.0,0.003783,0.003722,-0.001239,0.005135,-0.003898,-0.005209,0.004278,...,0.000144,-0.003363,-0.003075,0.001357,-0.001675,-0.002750,-0.001228,-0.004626,0.002300,-0.005839
2,user_A00181966XZUX7KEGYLH,-0.009555,1.0,0.001137,-0.001072,0.000820,-0.000663,-0.001608,-0.001077,0.001597,...,-0.001693,0.000767,-0.000952,-0.001741,0.001006,-0.001582,0.001079,-0.001251,-0.001055,-0.001230
3,user_A0019088YM52JB45AS96,-0.005492,1.0,-0.000076,0.000079,-0.000067,0.000154,0.000070,0.000082,-0.000081,...,0.000093,-0.000071,-0.000081,-0.000087,-0.000123,0.000099,-0.000078,-0.000156,0.000111,0.000082
4,user_A00231762M7PUF3V3ZBI,-0.005500,1.0,-0.000172,-0.000066,-0.000134,0.000041,0.000176,-0.000002,0.000129,...,0.000139,0.000197,-0.000080,0.000271,-0.000257,-0.000147,-0.000143,0.000321,0.000206,-0.000136

In [ ]:
csj_emb_dict = {}
for i in range(len(csj_emb)):
    k = csj_emb.iloc[i, 0]
    v = list(csj_emb.iloc[i, 3:].values)
    csj_emb_dict[k] = v

In [ ]:
csj_interaction_log['user_embedding'] = csj_interaction_log['reviewerID'].map(csj_emb_dict)
csj_interaction_log['item_embedding'] = csj_interaction_log['asin'].map(csj_emb_dict)

In [ ]:
csj_interaction_log.head()

In [ ]:
with open('./input/csj_lightfm.pickle', 'wb') as pf:
    pickle.dump(csj_interaction_log, pf)

In [22]:
# hk

In [24]:
hk_interaction_log = pd.read_csv('../../CPR/input/hk_train_input.txt', header=None, sep='\t')

In [25]:
hk_interaction_log['user_embedding'] = 0
hk_interaction_log['item_embedding'] = 0
hk_interaction_log.columns=['userID', 'itemID', 'rating', 'user_embedding', 'item_embedding']
hk_interaction_log.head()

,userID,itemID,rating,user_embedding,item_embedding
0,user_A0010876CNE3ILIM9HV0,B009HVH4XO,0.693147,0,0
1,user_A001170867ZBE9FORRQL,B00FDN70CU,0.693147,0,0
2,user_A001170867ZBE9FORRQL,B00G749EL4,0.693147,0,0
3,user_A001170867ZBE9FORRQL,B00MX4XM1U,0.693147,0,0
4,user_A001170867ZBE9FORRQL,B00OPET1ZM,0.693147,0,0

In [26]:
hk_emb = pd.read_csv('../BPR/graph/hk_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
hk_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_A0010876CNE3ILIM9HV0,-0.006576,1.0,-0.008371,0.000479,-0.001072,0.002699,-0.001521,-0.001136,0.002239,...,0.001995,-0.001720,0.001716,0.003035,-0.000198,-0.001245,0.005680,-0.004739,-0.001973,-0.000102
1,user_A001170867ZBE9FORRQL,-0.017046,1.0,0.000526,-0.000370,0.000198,-0.000400,0.000531,-0.000469,-0.000126,...,0.000608,0.000584,-0.000423,0.000441,0.000719,0.000549,-0.000513,0.000438,0.000477,-0.000411
2,user_A0013346O7Y8B4DKHKAG,-0.005938,1.0,0.000129,0.000281,0.000065,0.000215,-0.000033,-0.000095,0.000104,...,-0.000040,0.000019,0.000059,0.000003,-0.000035,-0.000198,-0.000008,0.000056,0.000173,0.000083
3,user_A00231762M7PUF3V3ZBI,-0.008478,1.0,-0.000215,0.000434,-0.000179,-0.000012,-0.000029,0.000073,0.000509,...,-0.000143,-0.000188,0.000332,-0.000222,-0.000328,-0.000119,0.000259,-0.000224,-0.000216,0.000345
4,user_A0034986DWR7WEDQN0GV,-0.010438,1.0,0.000152,-0.000633,0.000508,0.001171,-0.000692,0.001260,-0.000116,...,-0.000292,0.000216,0.001234,-0.000890,-0.000596,0.000030,0.000675,-0.001225,-0.000738,-0.000052

In [ ]:
hk_emb_dict = {}
for i in range(len(hk_emb)):
    k = hk_emb.iloc[i, 0]
    v = list(hk_emb.iloc[i, 3:].values)
    hk_emb_dict[k] = v

In [ ]:
hk_interaction_log['user_embedding'] = hk_interaction_log['reviewerID'].map(hk_emb_dict)
hk_interaction_log['item_embedding'] = hk_interaction_log['asin'].map(hk_emb_dict)

In [ ]:
hk_interaction_log.head()

In [ ]:
with open('./input/hk_lightfm.pickle', 'wb') as pf:
    pickle.dump(hk_interaction_log, pf)

In [ ]:
hk_total_item_set = set(hk_interaction_log.asin)
total_hk_item_emb = {}
for item in hk_total_item_set:
    total_hk_item_emb[item] = hk_emb_dict[item]

In [ ]:
with open('./input/hk_item_emb_dict.pickle', 'wb') as pf:
    pickle.dump(total_hk_item_emb, pf)

In [ ]:
with open('./input/hk_emb_dict.pickle', 'wb') as pf:
    pickle.dump(hk_emb_dict, pf)

In [ ]:
# mt

In [27]:
mt_interaction_log = pd.read_csv('../../CPR/input/all_mt_train_input.txt', header=None, sep='\t')

In [28]:
mt_interaction_log['user_embedding'] = 0
mt_interaction_log['item_embedding'] = 0
mt_interaction_log.columns=['reviewerID', 'asin', 'rating', 'user_embedding', 'item_embedding']
mt_interaction_log.head()

,reviewerID,asin,rating,user_embedding,item_embedding
0,user_A0040548BPHKXMHH3NTI,B00OV3VGP0,0.693147,0,0
1,user_A0149220O8WD7KG3O5XR,6301971663,0.693147,0,0
2,user_A0149220O8WD7KG3O5XR,6303574289,0.693147,0,0
3,user_A0149220O8WD7KG3O5XR,B000063V8R,0.693147,0,0
4,user_A0149220O8WD7KG3O5XR,B002D1XKB0,0.693147,0,0

In [29]:
mt_emb = pd.read_csv('../BPR/graph/mt_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
mt_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_A0040548BPHKXMHH3NTI,-0.033432,1.0,-0.023838,-0.009214,-0.048376,-0.031890,-0.046792,0.061089,-0.033751,...,0.019943,-0.023573,0.026448,0.003007,-0.051380,0.051904,0.013035,-0.012717,0.032067,-0.030978
1,user_A0149220O8WD7KG3O5XR,-0.125520,1.0,0.027297,0.067382,-0.104245,-0.079694,-0.016469,0.057503,-0.085916,...,-0.096791,0.051248,0.037731,-0.006801,-0.090068,0.090732,0.037283,-0.072010,-0.021784,0.006124
2,user_A0160612BLIWRHROHLLE,-0.130913,1.0,-0.038183,-0.019874,-0.013799,0.004540,-0.030067,0.039493,-0.020630,...,-0.008322,-0.019796,-0.009003,-0.014311,-0.019402,0.061959,-0.012574,0.004398,-0.030346,0.035916
3,user_A0221881VJG1DV9M63H2,-0.191316,1.0,0.042464,-0.045486,-0.030667,0.038922,-0.050954,-0.027719,0.059877,...,-0.054860,-0.041923,-0.015751,0.010252,0.011621,-0.070946,0.026423,-0.010685,0.070757,-0.022476
4,user_A0343241M6Q8B2UORS7,-0.136484,1.0,-0.055497,-0.030913,-0.001719,-0.002286,-0.009595,-0.042525,0.063675,...,0.015953,-0.018885,-0.008526,-0.004471,0.006808,-0.028258,-0.061651,0.036062,-0.012245,0.040575

In [ ]:
mt_emb_dict = {}
for i in range(len(mt_emb)):
    k = mt_emb.iloc[i, 0]
    v = list(mt_emb.iloc[i, 3:].values)
    mt_emb_dict[k] = v

In [ ]:
mt_interaction_log['user_embedding'] = mt_interaction_log['reviewerID'].map(mt_emb_dict)
mt_interaction_log['item_embedding'] = mt_interaction_log['asin'].map(mt_emb_dict)

In [ ]:
mt_interaction_log.head()

In [ ]:
with open('./input/mt_lightfm.pickle', 'wb') as pf:
    pickle.dump(mt_interaction_log, pf)

In [ ]:
# books

In [30]:
books_interaction_log = pd.read_csv('../../CPR/input/books_train_input.txt', header=None, sep='\t')

In [31]:
books_interaction_log['user_embedding'] = 0
books_interaction_log['item_embedding'] = 0
books_interaction_log.columns=['reviewerID', 'asin', 'rating', 'user_embedding', 'item_embedding']
books_interaction_log.head()

,reviewerID,asin,rating,user_embedding,item_embedding
0,user_A00037304EKN1SJNQV5A,0007433298,0.693147,0,0
1,user_A00037304EKN1SJNQV5A,0062073184,0.693147,0,0
2,user_A00037304EKN1SJNQV5A,0062320084,0.693147,0,0
3,user_A00037304EKN1SJNQV5A,0062320165,0.693147,0,0
4,user_A00037304EKN1SJNQV5A,0385541171,0.693147,0,0

In [32]:
books_emb = pd.read_csv('../BPR/graph/books_lightfm_bpr_10e-5.txt', header=None, sep=' ', skiprows=1)
books_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,user_A00037304EKN1SJNQV5A,-0.007202,1.0,-0.002074,-0.001041,-0.001903,-0.001796,-0.001208,-0.001082,-0.001201,...,-0.000526,0.001207,-0.001304,0.001243,0.001535,0.001064,-0.000526,-0.001692,-0.001501,0.001670
1,user_A000392684P4JNLQRBBW,-0.004858,1.0,0.000225,0.000098,0.000153,0.000185,0.000117,0.000103,0.000166,...,0.000065,-0.000110,0.000105,-0.000111,-0.000140,-0.000108,0.000073,0.000155,0.000140,-0.000213
2,user_A00123765A9OUFUDUB1J,-0.004335,1.0,0.000521,0.000277,0.000588,0.000405,0.000322,0.000281,0.000285,...,0.000124,-0.000330,0.000457,-0.000340,-0.000437,-0.000270,0.000147,0.000374,0.000374,-0.000422
3,user_A0015332H21AK8WZ0ZCS,-0.003757,1.0,-0.001200,-0.000605,-0.001227,-0.001086,-0.000705,-0.000618,-0.000738,...,-0.000344,0.000709,-0.001068,0.000717,0.000904,0.000605,-0.000387,-0.000908,-0.000808,0.001095
4,user_A0020356UF96ZV361ST,-0.013442,1.0,0.000517,0.000304,0.000485,0.000388,0.000332,0.000300,0.000217,...,0.000169,-0.000349,0.000281,-0.000367,-0.000433,-0.000284,0.000189,0.000350,0.000222,-0.000276

In [ ]:
books_emb_dict = {}
for i in range(len(books_emb)):
    k = books_emb.iloc[i, 0]
    v = list(books_emb.iloc[i, 3:].values)
    books_emb_dict[k] = v

In [ ]:
books_interaction_log['user_embedding'] = books_interaction_log['reviewerID'].map(books_emb_dict)
books_interaction_log['item_embedding'] = books_interaction_log['asin'].map(books_emb_dict)

In [ ]:
books_interaction_log.head()

In [ ]:
with open('./input/books_lightfm.pickle', 'wb') as pf:
    pickle.dump(books_interaction_log, pf)

In [ ]:
books_total_item_set = set(books_interaction_log.asin)
total_books_item_emb = {}
for item in books_total_item_set:
    total_books_item_emb[item] = books_emb_dict[item]

In [ ]:
with open('./input/books_item_emb_dict.pickle', 'wb') as pf:
    pickle.dump(total_books_item_emb, pf)

In [ ]:
with open('./input/books_emb_dict.pickle', 'wb') as pf:
    pickle.dump(books_emb_dict, pf)